version: 2
registries:
  chainguard: # Define access for a private registry
    type: docker-registry
    url: cgr.dev
    token: ${{CGR_AUTH_TOKEN}}
updates:
  - package-ecosystem: "docker"
    directory: "/"
    registries:
      - chainguard
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
