version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/" # Location of Dockerfiles or Kubernetes manifests
    schedule:
      interval: "weekly" # Adjust as needed: daily, weekly, or monthly
    open-pull-requests-limit: 5
allow:
  - dependency-name: "go-msft-fips"
    versions: ["1.20.*"]