version: 2
registries:
  dockerhub: # Define access for a private registry
    type: docker-registry
    url: cgr.dev
    username: {{secrets.PULL_TOKEN_ID}}
    password: ${{secrets.PULL_TOKEN_PW}}
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5