version: 2
# registries:
#   chainguard:
#     type: docker-registry
#     url: cgr.dev
#     username: ${{secrets.PULL_TOKEN_ID}}
#     password: ${{secrets.PULL_TOKEN_PW}}
updates:
  - package-ecosystem: "docker"
    directory: "/test.*/"
    # registries:
    #   - chainguard
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
